version: '3.8'
services:
  auth:
    container_name: auth
    image: id.dkr.ecr.us-east-2.amazonaws.com/{folderName}/auth:latest
    ports:
      - 8008:8008
    env_file:
      - .env.docker
    depends_on:
      - redis
      - mongodb
    pull_policy: always

  user-profile:
    container_name: user-profile
    image: id.dkr.ecr.us-east-2.amazonaws.com/{folderName}/user-profile:latest
    ports:
      - 8009:8009
    env_file:
      - .env.docker
    depends_on:
      - redis
      - mongodb
    pull_policy: always

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=mobile-app
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
